In [97]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.io as sio
from scipy.io import loadmat

<h2> NCA_Cells

In [2]:
mat_data = sio.loadmat('../../Data/imbalanced performance/Full factorial design of experiments dataset for parallel-connected lithium-ion cells imbalanced performance investigation/Parallel-connected module experimental campaign/1_Single_cell_characterisation/Aged_cells/HPPC_MS/HPPC_MultiSine_GS3.mat')
print(mat_data.keys())
print(mat_data['TempData'])

dict_keys(['__header__', '__version__', '__globals__', 'CurrentData', 'VoltageData', 'TimeData', 'StepIndex', 'CycleIndex', 'TempData'])
[[24.04170227]
 [23.95568085]
 [23.92630196]
 ...
 [24.19558525]
 [24.19558525]
 [24.19558525]]


In [3]:
HPPC = sio.loadmat('../../Data/imbalanced performance/Full factorial design of experiments dataset for parallel-connected lithium-ion cells imbalanced performance investigation/Parallel-connected module experimental campaign/1_Single_cell_characterisation/NCA_cells/HPPC_MS/HPPC_MultiSine_F1.mat')
print(HPPC.keys())
voltage = pd.DataFrame(HPPC["VoltageData"])
print(voltage)

dict_keys(['__header__', '__version__', '__globals__', 'CurrentData', 'VoltageData', 'TimeData', 'StepIndex', 'CycleIndex', 'TempData'])
              0
0      4.198920
1      4.198888
2      4.198831
3      4.198893
4      4.198682
...         ...
71304  3.319942
71305  3.319834
71306  3.319955
71307  3.319834
71308  3.319830

[71309 rows x 1 columns]


In [4]:
CurrentData = pd.DataFrame(HPPC["CurrentData"])
print(HPPC["CurrentData"])

min = CurrentData.min()
max = CurrentData.max()

print(min)
print(max)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
0   -19.288673
dtype: float64
0    6.730835
dtype: float64


In [5]:
TempData = pd.DataFrame(HPPC["TempData"])
print(TempData)
min = TempData.min()
max = TempData.max()

print(min)
print(max)

               0
0      23.254124
1      23.277819
2      23.277819
3      23.277819
4      23.310814
...          ...
71304  23.473037
71305  23.473021
71306  23.473021
71307  23.473021
71308  23.473021

[71309 rows x 1 columns]
0    22.955317
dtype: float64
0    26.202137
dtype: float64


In [6]:
StepIndex = pd.DataFrame(HPPC["StepIndex"])
print(StepIndex)
min = StepIndex.min()
max = StepIndex.max()

print(min)
print(max)

        0
0       9
1       9
2       9
3       9
4       9
...    ..
71304  22
71305  22
71306  22
71307  22
71308  22

[71309 rows x 1 columns]
0    9
dtype: uint8
0    22
dtype: uint8


In [7]:
NMC = sio.loadmat('../../Data/imbalanced performance/Full factorial design of experiments dataset for parallel-connected lithium-ion cells imbalanced performance investigation/Parallel-connected module experimental campaign/1_Single_cell_characterisation/NMC_cells/Pseudo_OCV/OCVDis_P2.mat')
print(NMC.keys())
print(NMC['OCV'])

dict_keys(['__header__', '__version__', '__globals__', 'TimeData', 'CurrentData', 'OCV', 'TempData'])
[[4.17760038]
 [4.1764679 ]
 [4.1756072 ]
 ...
 [2.50636649]
 [2.50317073]
 [2.49998546]]


In [8]:
Pseudo_OCV = sio.loadmat('../../Data/imbalanced performance/Full factorial design of experiments dataset for parallel-connected lithium-ion cells imbalanced performance investigation/Parallel-connected module experimental campaign/1_Single_cell_characterisation/NCA_cells/Pseudo_OCV/OCVDis_F1.mat')
print(Pseudo_OCV.keys())
print(Pseudo_OCV['OCV'])
print(Pseudo_OCV['TempData'])

dict_keys(['__header__', '__version__', '__globals__', 'TimeData', 'CurrentData', 'OCV', 'TempData'])
[[4.17623663]
 [4.17505026]
 [4.17401934]
 ...
 [2.50364828]
 [2.50034904]
 [2.49999332]]
[[23.34585369]
 [23.37764168]
 [23.32587294]
 ...
 [23.52936341]
 [23.56640434]
 [23.53652763]]


<h2> 2 Hall Sensors

In [29]:
H2_calibration = sio.loadmat('../../Data/imbalanced performance/Full factorial design of experiments dataset for parallel-connected lithium-ion cells imbalanced performance investigation/Parallel-connected module experimental campaign/2_Hall_sensors_calibration/H2_Calibration.mat')
print(list(H2_calibration.keys()))

['__header__', '__version__', '__globals__', 'None', '__function_workspace__']


In [31]:
data = loadmat('../../Data/imbalanced performance/Full factorial design of experiments dataset for parallel-connected lithium-ion cells imbalanced performance investigation/Parallel-connected module experimental campaign/2_Hall_sensors_calibration/H3_Calibration_struct.mat', struct_as_record=True, simplify_cells=True)
print(data.keys())
print(data["Data_struct"].keys())

dict_keys(['__header__', '__version__', '__globals__', 'Data_struct'])
dict_keys(['Test_Times', 'Step_Times', 'Step_Index', 'Cycle_Index', 'CurrentA', 'HallVoltage', 'PowerSupplyVoltage', 'CellTempData', 'AmbientTempData'])


In [32]:
print(data['Data_struct']['Test_Times'])
print(len(data['Data_struct']['Test_Times']))

[1.00400000e-01 2.00500000e-01 3.00300000e-01 ... 2.45629088e+02
 2.45729488e+02 2.45730188e+02]
2463


In [25]:
print(data['Data_struct']['Step_Index'])
print(len(data['Data_struct']['Step_Index']))

[ 1  1  1 ... 13 13 13]
2463


In [26]:
print(data['Data_struct']['Step_Times'])
print(len(data['Data_struct']['Step_Times']))

[ 0.1003  0.2003  0.3001 ...  9.9    10.0002 10.0009]
2463


In [28]:
print(data['Data_struct']['Cycle_Index'])
print(len(data['Data_struct']['Cycle_Index']))

[1 1 1 ... 1 1 1]
2463


In [27]:
print(data['Data_struct']['CurrentA'])
print(len(data['Data_struct']['CurrentA']))

[0. 0. 0. ... 0. 0. 0.]
2463


In [33]:
print(data['Data_struct']['HallVoltage'])
print(len(data['Data_struct']['HallVoltage']))

[2.49139857 2.49061561 2.49069405 ... 2.4889698  2.4905026  2.4905026 ]
2463


In [34]:
print(data['Data_struct']['PowerSupplyVoltage'])
print(len(data['Data_struct']['PowerSupplyVoltage']))

[4.998384   4.99846077 4.9984951  ... 4.99659824 4.99783945 4.99783945]
2463


In [35]:
print(data['Data_struct']['CellTempData'])
print(len(data['Data_struct']['CellTempData']))

[22.42968941 22.42968941 22.42968941 ... 22.45749664 22.45749664
 22.45749664]
2463


In [36]:
print(data['Data_struct']['AmbientTempData'])
print(len(data['Data_struct']['AmbientTempData']))

[22.7454834  22.7454834  22.7454834  ... 22.82348633 22.82348633
 22.82348633]
2463


<h2> 3 Modeule-level experiments

In [85]:
Mixed_aged_0_T10_Data = loadmat('../../Data/imbalanced performance/Full factorial design of experiments dataset for parallel-connected lithium-ion cells imbalanced performance investigation/Parallel-connected module experimental campaign/3_Module_level_experiments/Processed_data/Mixed_cells/Aged/R_0/T_10/M1_Mixed_Aged_R0_T10_fixed.mat', struct_as_record=True, simplify_cells=True)
print(Mixed_aged_0_T10_Data.keys())
print(Mixed_aged_0_T10_Data['Data_processed'].keys())
print(Mixed_aged_0_T10_Data['Data_processed']['Data'].keys())
print(Mixed_aged_0_T10_Data['Data_processed']['Data']['Test_Times'])
print(Mixed_aged_0_T10_Data['Data_processed']['Data']['VoltageV'])

dict_keys(['__header__', '__version__', '__globals__', 'Data_processed', '__function_workspace__'])
dict_keys(['Data', 'Cells_name'])
dict_keys(['Test_Times', 'Step_Times', 'Step_Index', 'Cycle_Index', 'VoltageV', 'CurrentA', 'TemperatureC_Cell_1', 'TemperatureC_Cell_2', 'TemperatureC_Cell_3', 'TemperatureC_Cell_4', 'Ambient_TemperatureC', 'CurrentA_Cell_1', 'CurrentA_Cell_2', 'CurrentA_Cell_3', 'CurrentA_Cell_4'])
[1.00030000e+00 2.00030000e+00 3.00020000e+00 ... 4.40061112e+04
 4.40071113e+04 4.40073912e+04]
[3.57247663 3.57260275 3.57241368 ... 4.20037413 4.20005894 4.19999599]


In [ ]:
Mixed_aged_0_T10_Data_fixed = loadmat('../../Data/imbalanced performance/Full factorial design of experiments dataset for parallel-connected lithium-ion cells imbalanced performance investigation/Parallel-connected module experimental campaign/3_Module_level_experiments_fixed/Processed_data/Mixed_cells/Aged/R_0/T_10/M1_Mixed_Aged_R0_T10.mat', struct_as_record=True, simplify_cells=True)
print(Mixed_aged_0_T10_Data_fixed.keys())
print(Mixed_aged_0_T10_Data_fixed['Data_processed'].keys())
print(Mixed_aged_0_T10_Data_fixed['Data_processed']['Data'].keys())
print(Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['Test_Times'])
print(Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['VoltageV'])

dict_keys(['__header__', '__version__', '__globals__', 'Data_processed', '__function_workspace__'])
dict_keys(['Data', 'Cells_name'])
dict_keys(['Test_Times', 'Step_Times', 'Step_Index', 'Cycle_Index', 'VoltageV', 'CurrentA', 'TemperatureC_Cell_1', 'TemperatureC_Cell_2', 'TemperatureC_Cell_3', 'TemperatureC_Cell_4', 'Ambient_TemperatureC', 'CurrentA_Cell_1', 'CurrentA_Cell_2', 'CurrentA_Cell_3', 'CurrentA_Cell_4'])
[1.00030000e+00 2.00030000e+00 3.00020000e+00 ... 4.40061112e+04
 4.40071113e+04 4.40073912e+04]
[1.00030000e+00 2.00030000e+00 3.00020000e+00 ... 4.40061112e+04
 4.40071113e+04 4.40073912e+04]
[3.57247663 3.57260275 3.57241368 ... 4.20037413 4.20005894 4.19999599]


In [88]:
StepIndex = Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['Step_Index']
min = StepIndex.min()
max = StepIndex.max()

print(min)
print(max)
print(StepIndex)

1
8
[1 1 1 ... 8 8 8]


In [89]:
Cycle_Index = Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['Cycle_Index']
min = Cycle_Index.min()
max = Cycle_Index.max()

print(min)
print(max)
print(Cycle_Index)

1
1
[1 1 1 ... 1 1 1]


In [90]:
VoltageV = Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['VoltageV']
min = VoltageV.min()
max = VoltageV.max()

print(min)
print(max)
print(VoltageV)

2.4998815059661865
4.2010674476623535
[3.57247663 3.57260275 3.57241368 ... 4.20037413 4.20005894 4.19999599]


In [91]:
CurrentA = Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['CurrentA']
min = CurrentA.min()
max = CurrentA.max()

print(min)
print(max)
print(CurrentA)

-14.588447570800781
6.581940174102783
[0.         0.         0.         ... 1.00498211 1.0100174  0.99989939]


In [92]:
TemperatureC_Cell_1 = Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['TemperatureC_Cell_1']
min = TemperatureC_Cell_1.min()
max = TemperatureC_Cell_1.max()

print(min)
print(max)
print(TemperatureC_Cell_1)

9.522167702575512
20.016721725463867
[19.97093773 19.97093773 20.01672173 ... 10.16082627 10.23292011
 10.28531872]


In [93]:
TemperatureC_Cell_2 = Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['TemperatureC_Cell_2']
min = TemperatureC_Cell_2.min()
max = TemperatureC_Cell_2.max()

print(min)
print(max)
print(TemperatureC_Cell_2)

9.720147846984405
20.11361476296033
[20.07918358 20.07918358 20.002285   ... 10.50720828 10.431919
 10.43191147]


In [94]:
Ambient_TemperatureC = Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['Ambient_TemperatureC']
min = Ambient_TemperatureC.min()
max = Ambient_TemperatureC.max()

print(min)
print(max)
print(Ambient_TemperatureC)

9.992251027451836
19.57393832185737
[19.45100594 19.45100594 19.56185913 ... 10.43354049 10.47611383
 10.47611809]


In [95]:
CurrentA_Cell_1 = Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['CurrentA_Cell_1']
min = CurrentA_Cell_1.min()
max = CurrentA_Cell_1.max()

print(min)
print(max)
print(CurrentA_Cell_1)

-5.164483448510651
1.9568628920217463
[0.34585134 0.342995   0.29787813 ... 0.24701766 0.25090272 0.24638453]


In [96]:
CurrentA_Cell_2 = Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['CurrentA_Cell_2']
min = CurrentA_Cell_2.min()
max = CurrentA_Cell_2.max()

print(min)
print(max)
print(CurrentA_Cell_2)

-5.223058381147453
1.7657361930000661
[-0.27813696 -0.27750615 -0.32376799 ...  0.33235415  0.33864047
  0.33637907]
