In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.io as sio
from scipy.io import loadmat
from cleaned_preprocess import IndividualProcess, CommonProcesses, ModularProcesses

<h2> NCA_Cells

In [2]:
HPPC_mat = sio.loadmat('../../Data/imbalanced performance/Full factorial design of experiments dataset for parallel-connected lithium-ion cells imbalanced performance investigation/Parallel-connected module experimental campaign/1_Single_cell_characterisation/Aged_cells/HPPC_MS/HPPC_MultiSine_GS3.mat')
OCV_mat = sio.loadmat('../../Data/imbalanced performance/Full factorial design of experiments dataset for parallel-connected lithium-ion cells imbalanced performance investigation/Parallel-connected module experimental campaign/1_Single_cell_characterisation/Aged_cells/Pseudo_OCV/OCVDis_GS3.mat')
print(HPPC_mat.keys())
print(OCV_mat.keys())
HPPC_pd = pd.DataFrame(
    {
    'CurrentData' : HPPC_mat['CurrentData'].squeeze(),
    'VoltageData': HPPC_mat['VoltageData'].squeeze(), 
    'TimeData': HPPC_mat['TimeData'].squeeze(), 
    'StepIndex': HPPC_mat['StepIndex'].squeeze(), 
    'CycleIndex': HPPC_mat['CycleIndex'].squeeze(), 
    'TempData': HPPC_mat['TempData'].squeeze()
    }
)
OCV_pd = pd.DataFrame(
    {
    'TimeData' : OCV_mat['TimeData'].squeeze(),
    'CurrentData': OCV_mat['CurrentData'].squeeze(), 
    'OCV': OCV_mat['OCV'].squeeze(), 
    'TempData': OCV_mat['TempData'].squeeze(), 
    }
)
print(HPPC_pd.head(10002))
print(OCV_pd.head(12))



dict_keys(['__header__', '__version__', '__globals__', 'CurrentData', 'VoltageData', 'TimeData', 'StepIndex', 'CycleIndex', 'TempData'])
dict_keys(['__header__', '__version__', '__globals__', 'TimeData', 'CurrentData', 'OCV', 'TempData'])
       CurrentData  VoltageData     TimeData  StepIndex  CycleIndex   TempData
0         0.000000     4.197761     0.000000          9           1  24.041702
1         0.000000     4.197635     1.000300          9           1  23.955681
2         0.000000     4.197824     2.000100          9           1  23.926302
3         0.000000     4.197635     3.000400          9           1  23.979719
4         0.000000     4.197635     4.000000          9           1  24.001940
...            ...          ...          ...        ...         ...        ...
9997      1.611389     4.103726  7802.933892         17           1  24.207268
9998      1.706421     4.104735  7803.034292         17           1  24.207268
9999      1.706421     4.105744  7803.134092      

In [3]:
mat_data = sio.loadmat('../../Data/imbalanced performance/Full factorial design of experiments dataset for parallel-connected lithium-ion cells imbalanced performance investigation/Parallel-connected module experimental campaign/1_Single_cell_characterisation/Aged_cells/HPPC_MS/HPPC_MultiSine_GS3.mat')
print(mat_data.keys())
print(mat_data['TempData'])

dict_keys(['__header__', '__version__', '__globals__', 'CurrentData', 'VoltageData', 'TimeData', 'StepIndex', 'CycleIndex', 'TempData'])
[[24.04170227]
 [23.95568085]
 [23.92630196]
 ...
 [24.19558525]
 [24.19558525]
 [24.19558525]]


In [4]:
cells = IndividualProcess.getCells()
for i in cells:
    print(i[1]["StepIndex"][8000])

13
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17


In [5]:
largeDataSet = IndividualProcess.getLongCellDataset()
print(largeDataSet)

        CellID  CurrentData  VoltageData   TempData  StepIndex  CycleIndex  \
0          GS3          0.0     4.197761  24.041702          9           1   
1          GS3          0.0     4.197635  23.955681          9           1   
2          GS3          0.0     4.197824  23.926302          9           1   
3          GS3          0.0     4.197635  23.979719          9           1   
4          GS3          0.0     4.197635  24.001940          9           1   
...        ...          ...          ...        ...        ...         ...   
2711537    F18          0.0     3.319781  22.857420         22           9   
2711538    F18          0.0     3.319725  22.857420         22           9   
2711539    F18          0.0     3.319683  22.857420         22           9   
2711540    F18          0.0     3.319831  22.857420         22           9   
2711541    F18          0.0     3.319834  22.857420         22           9   

             TimeData  
0            0.000000  
1            1.

In [6]:
largeDataSet = IndividualProcess.getLongCellDataset()
dfs = {
    key: group
    for key, group in largeDataSet.groupby("StepIndex")
}
stats = {
    k: (v["CurrentData"].min(), v["CurrentData"].max())
    for k, v in dfs.items()
}
print(stats)

{9: (0.0, 0.0), 10: (-4.850522041320801, -4.848125457763672), 11: (0.0, 0.0), 12: (-2.6621036529541016, -2.6592206954956055), 13: (0.0, 0.0), 14: (1.99847412109375, 2.000821113586426), 15: (0.0, 0.0), 17: (-19.35711669921875, 2.23480224609375), 18: (-17.796875, 4.9144287109375), 19: (-17.921630859375, 6.765594482421875), 20: (-7.76300048828125, 6.1458282470703125), 21: (-3.78411865234375, 6.5678253173828125), 22: (0.0, 0.0)}


In [7]:
largeDataSet = IndividualProcess.getLongCellDataset()
cells = {
    key: group
    for key, group in largeDataSet.groupby("CellID")
}
for cell_id, cell_df in cells.items():
    dfs = {
        key: group
        for key, group in cell_df.groupby("StepIndex")
    }
    stats = {
        k: (v["CurrentData"].min(), v["CurrentData"].max())
        for k, v in dfs.items()
    }
    print(cell_id, stats)

F1 {9: (0.0, 0.0), 10: (-4.850522041320801, -4.850127220153809), 11: (0.0, 0.0), 12: (-2.6604318618774414, -2.6601295471191406), 13: (0.0, 0.0), 14: (2.0000133514404297, 2.00018310546875), 15: (0.0, 0.0), 17: (-19.288673400878906, 2.1991729736328125), 18: (-17.762672424316406, 4.8535919189453125), 19: (-17.872451782226562, 6.7308349609375), 20: (-7.7396087646484375, 6.1186065673828125), 21: (-3.7738189697265625, 6.5563507080078125), 22: (0.0, 0.0)}
F10 {9: (0.0, 0.0), 10: (-4.850485801696777, -4.850169658660889), 11: (0.0, 0.0), 12: (-2.6605730056762695, -2.6600499153137207), 13: (0.0, 0.0), 14: (2.0001697540283203, 2.0004043579101562), 15: (0.0, 0.0), 17: (-19.298812866210938, 2.2093353271484375), 18: (-17.75408935546875, 4.847900390625), 19: (-17.884124755859375, 6.728759765625), 20: (-7.7380523681640625, 6.1246795654296875), 21: (-3.7833251953125, 6.5599365234375), 22: (0.0, 0.0)}
F11 {9: (0.0, 0.0), 10: (-4.850483417510986, -4.850142955780029), 11: (0.0, 0.0), 12: (-2.6605129241943

In [8]:
stats = (
    largeDataSet
        .groupby(["CellID", "StepIndex"])["CurrentData"]
        .agg(min_value="min", max_value="max")
        .reset_index()
)
with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.width", None,
    "display.max_colwidth", None,
):
    print(stats)

    CellID  StepIndex  min_value  max_value
0       F1          9   0.000000   0.000000
1       F1         10  -4.850522  -4.850127
2       F1         11   0.000000   0.000000
3       F1         12  -2.660432  -2.660130
4       F1         13   0.000000   0.000000
5       F1         14   2.000013   2.000183
6       F1         15   0.000000   0.000000
7       F1         17 -19.288673   2.199173
8       F1         18 -17.762672   4.853592
9       F1         19 -17.872452   6.730835
10      F1         20  -7.739609   6.118607
11      F1         21  -3.773819   6.556351
12      F1         22   0.000000   0.000000
13     F10          9   0.000000   0.000000
14     F10         10  -4.850486  -4.850170
15     F10         11   0.000000   0.000000
16     F10         12  -2.660573  -2.660050
17     F10         13   0.000000   0.000000
18     F10         14   2.000170   2.000404
19     F10         15   0.000000   0.000000
20     F10         17 -19.298813   2.209335
21     F10         18 -17.754089

In [9]:
largeDataSet = IndividualProcess.getLongCellDataset()
dfs = {
    key: group
    for key, group in largeDataSet.groupby("StepIndex")
}
stats = {
    k: (len(v["CellID"].unique()))
    for k, v in dfs.items()
}
print(stats)

{9: 38, 10: 38, 11: 38, 12: 38, 13: 38, 14: 38, 15: 38, 17: 38, 18: 38, 19: 38, 20: 38, 21: 38, 22: 38}


In [10]:
HPPC = sio.loadmat('../../Data/imbalanced performance/Full factorial design of experiments dataset for parallel-connected lithium-ion cells imbalanced performance investigation/Parallel-connected module experimental campaign/1_Single_cell_characterisation/NCA_cells/HPPC_MS/HPPC_MultiSine_F1.mat')
print(HPPC.keys())
voltage = pd.DataFrame(HPPC["VoltageData"])
print(voltage)

dict_keys(['__header__', '__version__', '__globals__', 'CurrentData', 'VoltageData', 'TimeData', 'StepIndex', 'CycleIndex', 'TempData'])
              0
0      4.198920
1      4.198888
2      4.198831
3      4.198893
4      4.198682
...         ...
71304  3.319942
71305  3.319834
71306  3.319955
71307  3.319834
71308  3.319830

[71309 rows x 1 columns]


In [11]:
TimeData = pd.DataFrame(HPPC["TimeData"])
print(TimeData)

                 0
0          0.00000
1          0.99850
2          1.99950
3          2.99900
4          3.99910
...            ...
71304  40822.94516
71305  40823.04566
71306  40823.14526
71307  40823.24546
71308  40823.24676

[71309 rows x 1 columns]


In [12]:
TimeData = pd.DataFrame(HPPC["CycleIndex"])
print(TimeData)

       0
0      1
1      1
2      1
3      1
4      1
...   ..
71304  9
71305  9
71306  9
71307  9
71308  9

[71309 rows x 1 columns]


In [13]:
CurrentData = pd.DataFrame(HPPC["CurrentData"])
print(HPPC["CurrentData"])

min = CurrentData.min()
max = CurrentData.max()

print(min)
print(max)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
0   -19.288673
dtype: float64
0    6.730835
dtype: float64


In [14]:
TempData = pd.DataFrame(HPPC["TempData"])
print(TempData)
min = TempData.min()
max = TempData.max()

print(min)
print(max)

               0
0      23.254124
1      23.277819
2      23.277819
3      23.277819
4      23.310814
...          ...
71304  23.473037
71305  23.473021
71306  23.473021
71307  23.473021
71308  23.473021

[71309 rows x 1 columns]
0    22.955317
dtype: float64
0    26.202137
dtype: float64


In [15]:
StepIndex = pd.DataFrame(HPPC["StepIndex"])
print(StepIndex)
min = StepIndex.min()
max = StepIndex.max()

print(min)
print(max)

        0
0       9
1       9
2       9
3       9
4       9
...    ..
71304  22
71305  22
71306  22
71307  22
71308  22

[71309 rows x 1 columns]
0    9
dtype: uint8
0    22
dtype: uint8


In [16]:
NMC = sio.loadmat('../../Data/imbalanced performance/Full factorial design of experiments dataset for parallel-connected lithium-ion cells imbalanced performance investigation/Parallel-connected module experimental campaign/1_Single_cell_characterisation/NMC_cells/Pseudo_OCV/OCVDis_P2.mat')
print(NMC.keys())
print(NMC['OCV'])

dict_keys(['__header__', '__version__', '__globals__', 'TimeData', 'CurrentData', 'OCV', 'TempData'])
[[4.17760038]
 [4.1764679 ]
 [4.1756072 ]
 ...
 [2.50636649]
 [2.50317073]
 [2.49998546]]


In [17]:
Pseudo_OCV = sio.loadmat('../../Data/imbalanced performance/Full factorial design of experiments dataset for parallel-connected lithium-ion cells imbalanced performance investigation/Parallel-connected module experimental campaign/1_Single_cell_characterisation/NCA_cells/Pseudo_OCV/OCVDis_F1.mat')
print(Pseudo_OCV.keys())
print(Pseudo_OCV['OCV'])
print(Pseudo_OCV['TempData'])

dict_keys(['__header__', '__version__', '__globals__', 'TimeData', 'CurrentData', 'OCV', 'TempData'])
[[4.17623663]
 [4.17505026]
 [4.17401934]
 ...
 [2.50364828]
 [2.50034904]
 [2.49999332]]
[[23.34585369]
 [23.37764168]
 [23.32587294]
 ...
 [23.52936341]
 [23.56640434]
 [23.53652763]]


<h2> 2 Hall Sensors

In [18]:
H2_calibration = sio.loadmat('../../Data/imbalanced performance/Full factorial design of experiments dataset for parallel-connected lithium-ion cells imbalanced performance investigation/Parallel-connected module experimental campaign/2_Hall_sensors_calibration/H2_Calibration.mat')
print(list(H2_calibration.keys()))

['__header__', '__version__', '__globals__', 'None', '__function_workspace__']


In [19]:
data = loadmat('../../Data/imbalanced performance/Full factorial design of experiments dataset for parallel-connected lithium-ion cells imbalanced performance investigation/Parallel-connected module experimental campaign/2_Hall_sensors_calibration/H3_Calibration_struct.mat', struct_as_record=True, simplify_cells=True)
print(data.keys())
print(data["Data_struct"].keys())

dict_keys(['__header__', '__version__', '__globals__', 'Data_struct'])
dict_keys(['Test_Times', 'Step_Times', 'Step_Index', 'Cycle_Index', 'CurrentA', 'HallVoltage', 'PowerSupplyVoltage', 'CellTempData', 'AmbientTempData'])


In [20]:
print(data['Data_struct']['Test_Times'])
print(len(data['Data_struct']['Test_Times']))

[1.00400000e-01 2.00500000e-01 3.00300000e-01 ... 2.45629088e+02
 2.45729488e+02 2.45730188e+02]
2463


In [21]:
print(data['Data_struct']['Step_Index'])
print(len(data['Data_struct']['Step_Index']))

[ 1  1  1 ... 13 13 13]
2463


In [22]:
print(data['Data_struct']['Step_Times'])
print(len(data['Data_struct']['Step_Times']))

[ 0.1003  0.2004  0.3002 ...  9.9    10.0004 10.0011]
2463


In [23]:
print(data['Data_struct']['Cycle_Index'])
print(len(data['Data_struct']['Cycle_Index']))

[1 1 1 ... 1 1 1]
2463


In [24]:
print(data['Data_struct']['CurrentA'])
print(len(data['Data_struct']['CurrentA']))

[0. 0. 0. ... 0. 0. 0.]
2463


In [25]:
print(data['Data_struct']['HallVoltage'])
print(len(data['Data_struct']['HallVoltage']))

[2.49139857 2.49061561 2.49069405 ... 2.4889698  2.4905026  2.4905026 ]
2463


In [26]:
print(data['Data_struct']['PowerSupplyVoltage'])
print(len(data['Data_struct']['PowerSupplyVoltage']))

[4.998384   4.99846077 4.9984951  ... 4.99659824 4.99783945 4.99783945]
2463


In [27]:
print(data['Data_struct']['CellTempData'])
print(len(data['Data_struct']['CellTempData']))

[22.42968941 22.42968941 22.42968941 ... 22.45749664 22.45749664
 22.45749664]
2463


In [28]:
print(data['Data_struct']['AmbientTempData'])
print(len(data['Data_struct']['AmbientTempData']))

[22.7454834  22.7454834  22.7454834  ... 22.82348633 22.82348633
 22.82348633]
2463


<h2> 3 Modeule-level experiments

In [29]:
Mixed_aged_0_T10_Data = loadmat('../../Data/imbalanced performance/Full factorial design of experiments dataset for parallel-connected lithium-ion cells imbalanced performance investigation/Parallel-connected module experimental campaign/3_Module_level_experiments/Processed_data/Mixed_cells/Aged/R_0/T_10/M1_Mixed_Aged_R0_T10_fixed.mat', struct_as_record=True, simplify_cells=True)
Mixed_aged_0_T10_pd = pd.DataFrame(
    {
    'Test_Times' : Mixed_aged_0_T10_Data['Data_processed']['Data']['Test_Times'].squeeze(),
    'Step_Times': Mixed_aged_0_T10_Data['Data_processed']['Data']['Step_Times'].squeeze(), 
    'Step_Index': Mixed_aged_0_T10_Data['Data_processed']['Data']['Step_Index'].squeeze(), 
    'Cycle_Index': Mixed_aged_0_T10_Data['Data_processed']['Data']['Cycle_Index'].squeeze(), 
    'VoltageV': Mixed_aged_0_T10_Data['Data_processed']['Data']['VoltageV'].squeeze(), 
    'CurrentA': Mixed_aged_0_T10_Data['Data_processed']['Data']['CurrentA'].squeeze(),
    'TemperatureC_Cell_1' : Mixed_aged_0_T10_Data['Data_processed']['Data']['TemperatureC_Cell_1'].squeeze(),
    'TemperatureC_Cell_2': Mixed_aged_0_T10_Data['Data_processed']['Data']['TemperatureC_Cell_2'].squeeze(), 
    'TemperatureC_Cell_3': Mixed_aged_0_T10_Data['Data_processed']['Data']['TemperatureC_Cell_3'].squeeze(), 
    'TemperatureC_Cell_4': Mixed_aged_0_T10_Data['Data_processed']['Data']['TemperatureC_Cell_4'].squeeze(), 
    'Ambient_TemperatureC': Mixed_aged_0_T10_Data['Data_processed']['Data']['Ambient_TemperatureC'].squeeze(),
    'CurrentA_Cell_1' : Mixed_aged_0_T10_Data['Data_processed']['Data']['CurrentA_Cell_1'].squeeze(),
    'CurrentA_Cell_2': Mixed_aged_0_T10_Data['Data_processed']['Data']['CurrentA_Cell_2'].squeeze(), 
    'CurrentA_Cell_3': Mixed_aged_0_T10_Data['Data_processed']['Data']['CurrentA_Cell_3'].squeeze(), 
    'CurrentA_Cell_4': Mixed_aged_0_T10_Data['Data_processed']['Data']['CurrentA_Cell_4'].squeeze()
    }
)

print(Mixed_aged_0_T10_pd.head(10))

   Test_Times  Step_Times  Step_Index  Cycle_Index  VoltageV  CurrentA  \
0      1.0003      1.0002           1            1  3.572477       0.0   
1      2.0003      2.0002           1            1  3.572603       0.0   
2      3.0002      3.0001           1            1  3.572414       0.0   
3      4.0001      4.0000           1            1  3.571972       0.0   
4      5.0003      5.0002           1            1  3.572288       0.0   
5      6.0001      6.0000           1            1  3.572351       0.0   
6      7.0004      7.0003           1            1  3.572225       0.0   
7      8.0000      7.9999           1            1  3.572540       0.0   
8      9.0005      9.0004           1            1  3.571972       0.0   
9     10.0001     10.0000           1            1  3.572603       0.0   

   TemperatureC_Cell_1  TemperatureC_Cell_2  TemperatureC_Cell_3  \
0            19.970938            20.079184            20.310024   
1            19.970938            20.079184      

In [30]:
largeDataSet = ModularProcesses.getLongCellDatasetModular()
print(largeDataSet)
stats = (
    largeDataSet
        .groupby(["Cell", "aged", "Resistance", "StepIndex"])["CurrentA"]
        .agg(min_value="min", max_value="max")
        .reset_index()
)
with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.width", None,
    "display.max_colwidth", None,
):
    print(stats)

          Cell    aged  Resistance  Temp     TestTimes  StepTimes  CycleIndex  \
0        Mixed    Aged           0    10      1.000300     1.0002           1   
1        Mixed    Aged           0    10      2.000300     2.0002           1   
2        Mixed    Aged           0    10      3.000200     3.0001           1   
3        Mixed    Aged           0    10      4.000100     4.0000           1   
4        Mixed    Aged           0    10      5.000300     5.0002           1   
...        ...     ...         ...   ...           ...        ...         ...   
2402964    NMC  Unaged           3    40  47806.248448  3672.0001           1   
2402965    NMC  Unaged           3    40  47807.248548  3673.0002           1   
2402966    NMC  Unaged           3    40  47808.248548  3674.0002           1   
2402967    NMC  Unaged           3    40  47809.248848  3675.0005           1   
2402968    NMC  Unaged           3    40  47809.528348  3675.2800           1   

         StepIndex  Voltage

In [31]:
Mixed_aged_0_T10_Data = loadmat('../../Data/imbalanced performance/Full factorial design of experiments dataset for parallel-connected lithium-ion cells imbalanced performance investigation/Parallel-connected module experimental campaign/3_Module_level_experiments/Processed_data/Mixed_cells/Aged/R_0/T_10/M1_Mixed_Aged_R0_T10_fixed.mat', struct_as_record=True, simplify_cells=True)
print(Mixed_aged_0_T10_Data.keys())
print(Mixed_aged_0_T10_Data['Data_processed'].keys())
print(Mixed_aged_0_T10_Data['Data_processed']['Data'].keys())
print(Mixed_aged_0_T10_Data['Data_processed']['Data']['Test_Times'])
print(Mixed_aged_0_T10_Data['Data_processed']['Data']['VoltageV'])

dict_keys(['__header__', '__version__', '__globals__', 'Data_processed', '__function_workspace__'])
dict_keys(['Data', 'Cells_name'])
dict_keys(['Test_Times', 'Step_Times', 'Step_Index', 'Cycle_Index', 'VoltageV', 'CurrentA', 'TemperatureC_Cell_1', 'TemperatureC_Cell_2', 'TemperatureC_Cell_3', 'TemperatureC_Cell_4', 'Ambient_TemperatureC', 'CurrentA_Cell_1', 'CurrentA_Cell_2', 'CurrentA_Cell_3', 'CurrentA_Cell_4'])
[1.00030000e+00 2.00030000e+00 3.00020000e+00 ... 4.40061112e+04
 4.40071113e+04 4.40073912e+04]
[3.57247663 3.57260275 3.57241368 ... 4.20037413 4.20005894 4.19999599]


In [32]:
Mixed_aged_0_T10_Data_fixed = loadmat('../../Data/imbalanced performance/Full factorial design of experiments dataset for parallel-connected lithium-ion cells imbalanced performance investigation/Parallel-connected module experimental campaign/3_Module_level_experiments_fixed/Processed_data/Mixed_cells/Aged/R_0/T_10/M1_Mixed_Aged_R0_T10.mat', struct_as_record=True, simplify_cells=True)
print(Mixed_aged_0_T10_Data_fixed.keys())
print(Mixed_aged_0_T10_Data_fixed['Data_processed'].keys())
print(Mixed_aged_0_T10_Data_fixed['Data_processed']['Data'].keys())
print(Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['Test_Times'])
print(Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['VoltageV'])
print(len(Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['VoltageV']))
print(len(Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['Test_Times']))

dict_keys(['__header__', '__version__', '__globals__', 'Data_processed'])
dict_keys(['Data', 'Cells_name'])
dict_keys(['Test_Times', 'Step_Times', 'Step_Index', 'Cycle_Index', 'VoltageV', 'CurrentA', 'TemperatureC_Cell_1', 'TemperatureC_Cell_2', 'TemperatureC_Cell_3', 'TemperatureC_Cell_4', 'Ambient_TemperatureC', 'CurrentA_Cell_1', 'CurrentA_Cell_2', 'CurrentA_Cell_3', 'CurrentA_Cell_4'])
[1.00030000e+00 2.00030000e+00 3.00020000e+00 ... 4.40061112e+04
 4.40071113e+04 4.40073912e+04]
[3.57247663 3.57260275 3.57241368 ... 4.20037413 4.20005894 4.19999599]
44011
44011


In [33]:
print(Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['Test_Times'][0])
print(Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['Test_Times'][1])
print(Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['Test_Times'][2])
print(Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['Test_Times'][3])
print(Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['Test_Times'][30000])

1.0003
2.0003
3.0002
4.0001
29999.480327999998


In [34]:
StepIndex = Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['Step_Index']
min = StepIndex.min()
max = StepIndex.max()

print(min)
print(max)
print(StepIndex)

1
8
[1 1 1 ... 8 8 8]


In [35]:
Cycle_Index = Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['Cycle_Index']
min = Cycle_Index.min()
max = Cycle_Index.max()

print(min)
print(max)
print(Cycle_Index)

1
1
[1 1 1 ... 1 1 1]


In [36]:
VoltageV = Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['VoltageV']
min = VoltageV.min()
max = VoltageV.max()

print(min)
print(max)
print(VoltageV)

2.4998815059661865
4.2010674476623535
[3.57247663 3.57260275 3.57241368 ... 4.20037413 4.20005894 4.19999599]


In [37]:
CurrentA = Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['CurrentA']
min = CurrentA.min()
max = CurrentA.max()

print(min)
print(max)
print(CurrentA)

-14.588447570800781
6.581940174102783
[0.         0.         0.         ... 1.00498211 1.0100174  0.99989939]


In [38]:
TemperatureC_Cell_1 = Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['TemperatureC_Cell_1']
min = TemperatureC_Cell_1.min()
max = TemperatureC_Cell_1.max()

print(min)
print(max)
print(TemperatureC_Cell_1)

9.522167702575512
20.016721725463867
[19.97093773 19.97093773 20.01672173 ... 10.16082627 10.23292011
 10.28531872]


In [39]:
TemperatureC_Cell_2 = Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['TemperatureC_Cell_2']
min = TemperatureC_Cell_2.min()
max = TemperatureC_Cell_2.max()

print(min)
print(max)
print(TemperatureC_Cell_2)

9.720147846984405
20.11361476296033
[20.07918358 20.07918358 20.002285   ... 10.50720828 10.431919
 10.43191147]


In [40]:
Ambient_TemperatureC = Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['Ambient_TemperatureC']
min = Ambient_TemperatureC.min()
max = Ambient_TemperatureC.max()

print(min)
print(max)
print(Ambient_TemperatureC)

9.992251027451836
19.57393832185737
[19.45100594 19.45100594 19.56185913 ... 10.43354049 10.47611383
 10.47611809]


In [41]:
CurrentA_Cell_1 = Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['CurrentA_Cell_1']
min = CurrentA_Cell_1.min()
max = CurrentA_Cell_1.max()

print(min)
print(max)
print(CurrentA_Cell_1)

-5.164483448510651
1.9568628920217463
[0.34585134 0.342995   0.29787813 ... 0.24701766 0.25090272 0.24638453]


In [42]:
CurrentA_Cell_2 = Mixed_aged_0_T10_Data_fixed['Data_processed']['Data']['CurrentA_Cell_2']
min = CurrentA_Cell_2.min()
max = CurrentA_Cell_2.max()

print(min)
print(max)
print(CurrentA_Cell_2)

-5.223058381147453
1.7657361930000661
[-0.27813696 -0.27750615 -0.32376799 ...  0.33235415  0.33864047
  0.33637907]


In [43]:
print(Mixed_aged_0_T10_Data_fixed['Data_processed'].keys())
print(Mixed_aged_0_T10_Data_fixed['Data_processed']['Cells_name'].keys())

dict_keys(['Data', 'Cells_name'])
dict_keys(['Position_1', 'Position_2', 'Position_3', 'Position_4'])


In [44]:
Mixed_aged_0_T10_Data_clean = loadmat('../../Data/imbalanced performance/Full factorial design of experiments dataset for parallel-connected lithium-ion cells imbalanced performance investigation/Parallel-connected module experimental campaign/3_Module_level_experiments_fixed/Processed_data/Mixed_cells/Aged/R_0/T_10/M1_Mixed_Aged_R0_T10.mat', struct_as_record=True, simplify_cells=True)
print(Mixed_aged_0_T10_Data_clean.keys())
print(Mixed_aged_0_T10_Data_clean['Data_processed'].keys())
print(Mixed_aged_0_T10_Data_clean['Data_processed']['Cells_name'].keys())

dict_keys(['__header__', '__version__', '__globals__', 'Data_processed'])
dict_keys(['Data', 'Cells_name'])
dict_keys(['Position_1', 'Position_2', 'Position_3', 'Position_4'])


In [45]:
print(Mixed_aged_0_T10_Data_clean['Data_processed']['Cells_name']['Position_1'])
print(Mixed_aged_0_T10_Data_clean['Data_processed']['Cells_name']['Position_2'])
print(Mixed_aged_0_T10_Data_clean['Data_processed']['Cells_name']['Position_3'])
print(Mixed_aged_0_T10_Data_clean['Data_processed']['Cells_name']['Position_4'])

F6
GS3
P19
Y1
